# Generated by Django 5.2.1 on 2025-05-28 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('instructor', models.CharField(max_length=255)),
                ('credit_hours', models.IntegerField()),
                ('level', models.CharField(max_length=50)),
                ('keywords', models.TextField(blank=True)),
                ('prerequisites_txt', models.ManyToManyField(blank=True, to='course_dive.course')),
            ],
        ),
        migrations.CreateModel(
            name='Prerequisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequisite_links', to='course_dive.course')),
            ],
        ),
        migrations.CreateModel(
            name='CourseRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_date', models.DateTimeField(auto_now_add=True)),
                ('recommended_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_dive.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_dive.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('major', models.CharField(max_length=100)),
                ('minor', models.CharField(blank=True, max_length=100, null=True)),
                ('year', models.CharField(max_length=50)),
                ('exp_grad_year', models.IntegerField()),
                ('credits_completed', models.IntegerField()),
                ('interests', models.TextField()),
                ('completed_courses', models.ManyToManyField(related_name='completed_by', to='course_dive.course')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='course_dive.user')),
            ],
        ),
    ]
