# Generated by Django 5.2.1 on 2025-06-18 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_dive', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='prerequisites_txt',
            new_name='prerequisites',
        ),
    ]
