# Generated by Django 5.2.1 on 2025-06-18 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_dive', '0002_rename_prerequisites_txt_course_prerequisites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='course_dive.user'),
        ),
    ]
