# Generated by Django 5.2.1 on 2025-06-27 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_dive', '0005_alter_course_instructor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='major',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
