# Generated by Django 5.2.1 on 2025-06-27 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_dive', '0006_alter_userprofile_age_alter_userprofile_major'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='completed_courses',
            field=models.ManyToManyField(blank=True, related_name='completed_by', to='course_dive.course'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='exp_grad_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='interests',
            field=models.TextField(blank=True, null=True),
        ),
    ]
