# Generated by Django 5.2.1 on 2025-06-27 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_dive', '0007_alter_userprofile_completed_courses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='credits_completed',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
