# Generated by Django 5.2.1 on 2025-06-27 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_dive', '0009_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
