# Generated by Django 5.2.1 on 2025-06-27 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_dive', '0011_userprofile_diffuculty_preference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='diffuculty_preference',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='difficulty_preference',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
