# Generated by Django 5.2.1 on 2025-06-27 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_dive', '0012_remove_userprofile_diffuculty_preference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='crn',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='credit_hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, default='No description provided.'),
        ),
        migrations.AlterField(
            model_name='course',
            name='instructor',
            field=models.CharField(default='TBD', max_length=255),
        ),
        migrations.AlterField(
            model_name='course',
            name='keywords',
            field=models.TextField(blank=True, default='No keywords'),
        ),
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(default='Unknown', max_length=50),
        ),
    ]
