# Generated by Django 5.2.1 on 2025-06-27 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_dive', '0013_course_crn_course_department_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prerequisite',
        ),
    ]
