courses = {
    "American Studies": {
        "AMST202": {
            "title": "Early America",
            "credits": 1.0,
            "prereqs": [],
            "offered": ["Spring"],
            "gen_ed": ["Humanities"],
            "tags": [
                "History"
            ],  # Cross-listed as HIST 201:contentReference[oaicite:0]{index=0}:contentReference[oaicite:1]{index=1}
        },
        "AMST203": {
            "title": "Conflicts and Cultures in American Society",
            "credits": 1.0,
            "prereqs": [],
            "offered": ["Spring"],
            "gen_ed": ["Humanities"],
            "tags": [],
        },
        "AMST209": {
            "title": "African-American History",
            "credits": 1.0,
            "prereqs": [],
            "offered": ["Fall"],
            "gen_ed": ["Humanities"],
            "tags": [],
        },
        "AMST271": {
            "title": "Decentering and Re-centering History: Anthropology of Museums",
            "credits": 1.0,
            "prereqs": [],
            "offered": ["Fall"],
            "gen_ed": ["Social Sciences"],
            "tags": ["Anthropology"],
        },
        "AMST285": {
            "title": "Born in Blood: Violence and the Making of America",
            "credits": 1.0,
            "prereqs": [],
            "offered": ["Fall"],
            "gen_ed": ["Humanities"],
            "tags": [],
        },
        "AMST301": {
            "title": "American Studies Seminar",
            "credits": 1.0,
            "prereqs": [
                "AMST203"
            ],  # Major core seminar, typically taken after introductory courses
            "offered": ["Spring"],
            "gen_ed": ["Writing Emphasis 2"],
            "tags": [],
        },
    },
    "Anthropology": {
        "ANTH 101": {
            "title": "Introduction to Cultural Anthropology",
            "credits": 1.0,
            "prereqs": [],
            "offered": ["Fall", "Spring"],
            "gen_ed": ["Social Science"],
            "tags": [],
        },
        "ANTH 300": {
            "title": "Ethnographic Research Methods",
            "credits": 1.0,
            "prereqs": ["ANTH 101"],
            "offered": ["Alternate Years"],
            "gen_ed": ["Social Science"],
            "tags": [],
        },
        "ANTH 301": {
            "title": "History of Anthropological Theory",
            "credits": 1.0,
            "prereqs": ["ANTH 101"],
            "offered": ["Alternate Years"],
            "gen_ed": ["Social Science"],
            "tags": [],
        },
        "ANTH 253": {
            "title": "Urban Anthropology",
            "credits": 1.0,
            "prereqs": ["ANTH 101"],
            "offered": ["Spring"],
            "gen_ed": ["Social Science"],
            "tags": [],
        },
        "ANTH 317": {
            "title": "Anthropology of Magic, Sorcery, and Witchcraft",
            "credits": 1.0,
            "prereqs": ["ANTH 101"],
            "offered": ["Alternate Years"],
            "gen_ed": ["Social Science"],
            "tags": [],
        },
        "ANTH 401": {
            "title": "Senior Seminar in Anthropology",
            "credits": 1.0,
            "prereqs": ["Senior Standing"],
            "offered": ["Fall"],
            "gen_ed": ["Writing Emphasis 2"],
            "tags": [],
        },
    },
    "Art History": {
        "AHIS101": {
            "title": "History of Art in the West I",
            "credits": 1.0,
            "prereqs": [],
            "offered": ["Fall"],
            "gen_ed": ["Arts"],
            "tags": [],
        },
        "AHIS102": {
            "title": "History of Art in the West II",
            "credits": 1.0,
            "prereqs": [],
            "offered": ["Spring"],
            "gen_ed": ["Arts"],
            "tags": [],
        },
        "AHIS226": {
            "title": "Drinking, Dining, and Community in Antiquity",
            "credits": 1.0,
            "prereqs": [],
            "offered": ["Fall"],
            "gen_ed": ["Arts"],
            "tags": [],
        },
        "AHIS241": {
            "title": "Classical Ideals: The Human Body in Ancient Art",
            "credits": 1.0,
            "prereqs": [],
            "offered": ["Spring"],
            "gen_ed": ["Arts"],
            "tags": [
                "Classical Civilization",
                "Women, Gender, and Sexuality",
            ],  # Cross-referenced as CLCV 241 and WMGS:contentReference[oaicite:2]{index=2}
        },
        "AHIS361": {
            "title": "Seminar on Impressionism",
            "credits": 1.0,
            "prereqs": ["AHIS102"],
            "offered": ["Fall"],
            "gen_ed": ["Arts", "Writing Emphasis 2"],
            "tags": ["Drawing"],
        },
        "AHIS364": {
            "title": "Architectural Drawing",
            "credits": 1.0,
            "prereqs": [],
            "offered": ["Fall"],
            "gen_ed": ["Arts"],
            "tags": [
                "Architecture",
                "Engineering",
            ],  # Prerequisite for ENGR342 (cross-listed):contentReference[oaicite:3]{index=3}
        },
        "AHIS365": {
            "title": "Elements of Architectural Design",
            "credits": 1.0,
            "prereqs": ["AHIS364"],
            "offered": ["Spring"],
            "gen_ed": ["Arts"],
            "tags": ["Architecture"],
        },
    },
    "Biology": {
        "BIOL 140": {
            "title": "Biological Systems",
            "credits": 1.0,
            "prereqs": [],
            "offered": ["Fall"],
            "gen_ed": ["Natural Science"],
            "tags": [],
        },
        "BIOL 141": {
            "title": "Global Perspectives on Biodiversity and Conservation",
            "credits": 1.0,
            "prereqs": [],
            "offered": ["Spring"],
            "gen_ed": ["Natural Science"],
            "tags": [],
        },
        "BIOL 182L": {
            "title": "Evolution of Life (Introductory Biology I)",
            "credits": 1.25,  # includes lab
            "prereqs": [],
            "offered": ["Fall"],
            "gen_ed": ["Natural Science"],
            "tags": [],
        },
        "BIOL 183L": {
            "title": "The Cellular Basis of Life (Introductory Biology II)",
            "credits": 1.25,
            "prereqs": ["BIOL 182L"],
            "offered": ["Spring"],
            "gen_ed": ["Natural Science"],
            "tags": [],
        },
        "BIOL 119": {
            "title": "Nutrition: Food and Fads",
            "credits": 1.0,
            "prereqs": [],
            "offered": ["Alternate Years"],
            "gen_ed": ["Natural Science"],
            "tags": [],
        },
        "BIOL 120": {
            "title": "Genes, Clones, and Biotechnology",
            "credits": 1.0,
            "prereqs": [],
            "offered": ["Fall"],
            "gen_ed": ["Natural Science"],
            "tags": [],
        },
        "BIOL 122": {
            "title": "Toxicology",
            "credits": 1.0,
            "prereqs": [],
            "offered": ["Alternate Years"],
            "gen_ed": ["Natural Science"],
            "tags": [],
        },
        "BIOL 124": {
            "title": "Genes and Human Disease",
            "credits": 1.0,
            "prereqs": [],
            "offered": ["Spring"],
            "gen_ed": ["Natural Science"],
            "tags": [],
        },
        "BIOL 222L": {
            "title": "Invertebrate Zoology",
            "credits": 1.0,
            "prereqs": ["BIOL 182L", "BIOL 183L"],
            "offered": ["Alternate Years"],
            "gen_ed": ["Natural Science"],
            "tags": [],
        },
        "BIOL 224L": {
            "title": "Genetics",
            "credits": 1.0,
            "prereqs": ["BIOL 183L", "CHEM 112L"],
            "offered": ["Fall"],
            "gen_ed": ["Natural Science", "Writing Emphasis 2"],
            "tags": [],
        },
        "BIOL 226L": {
            "title": "Foundations & Techniques in Molecular Biology",
            "credits": 1.0,
            "prereqs": ["BIOL 183L", "CHEM 112L"],
            "offered": ["Spring"],
            "gen_ed": ["Natural Science", "Writing Emphasis 2"],
            "tags": [],
        },
        "BIOL 227L": {
            "title": "Cell Biology",
            "credits": 1.0,
            "prereqs": ["BIOL 183L", "CHEM 112L"],
            "offered": ["Fall"],
            "gen_ed": ["Natural Science"],
            "tags": [],
        },
        "BIOL 233": {
            "title": "Conservation Biology",
            "credits": 1.0,
            "prereqs": ["BIOL 182L"],
            "offered": ["Spring"],
            "gen_ed": ["Natural Science"],
            "tags": [],
        },
        "BIOL 302": {
            "title": "Amphibian Ecology and Conservation",
            "credits": 1.0,
            "prereqs": ["BIOL 233"],
            "offered": ["Alternate Years"],
            "gen_ed": ["Natural Science"],
            "tags": [],
        },
        "BIOL 308L": {
            "title": "Microbiology",
            "credits": 1.0,
            "prereqs": ["BIOL 224L"],
            "offered": ["Spring"],
            "gen_ed": ["Natural Science"],
            "tags": [],
        },
        "BIOL 310L": {
            "title": "Developmental Biology",
            "credits": 1.0,
            "prereqs": ["BIOL 224L"],
            "offered": ["Alternate Years"],
            "gen_ed": ["Natural Science"],
            "tags": [],
        },
        "BIOL 315L": {
            "title": "Vertebrate Zoology",
            "credits": 1.0,
            "prereqs": ["BIOL 182L", "BIOL 183L"],
            "offered": ["Alternate Years"],
            "gen_ed": ["Natural Science"],
            "tags": [],
        },
        "BIOL 317L": {
            "title": "Biochemistry",
            "credits": 1.0,
            "prereqs": ["BIOL 183L", "CHEM 212L"],
            "offered": ["Fall"],
            "gen_ed": ["Natural Science"],
            "tags": [],
        },
        "BIOL 319L": {
            "title": "Animal Physiology",
            "credits": 1.0,
            "prereqs": ["BIOL 183L", "CHEM 112L"],
            "offered": ["Alternate Years"],
            "gen_ed": ["Natural Science"],
            "tags": [],
        },
        "BIOL 324": {
            "title": "Advanced Molecular Approaches in Neurobiology",
            "credits": 1.0,
            "prereqs": ["BIOL 224L"],
            "offered": ["Alternate Years"],
            "gen_ed": ["Natural Science"],
            "tags": ["Neuroscience"],
        },
        "BIOL 333L": {
            "title": "Ecology",
            "credits": 1.0,
            "prereqs": ["BIOL 182L"],
            "offered": ["Alternate Years"],
            "gen_ed": ["Natural Science"],
            "tags": [],
        },
        "BIOL 429": {
            "title": "Behavioral Mechanisms of Ecology",
            "credits": 1.0,
            "prereqs": ["BIOL 333L"],
            "offered": ["Alternate Years"],
            "gen_ed": ["Natural Science"],
            "tags": [],
        },
        "BIOL 446": {
            "title": "Bacterial Pathogenesis",
            "credits": 1.0,
            "prereqs": ["BIOL 308L"],
            "offered": ["Alternate Years"],
            "gen_ed": ["Natural Science"],
            "tags": [],
        },
    },
    "Chemistry": {
        "CHEM 111L": {
            "title": "Introductory Chemistry I",
            "credits": 1.25,  # includes lab
            "prereqs": [],
            "offered": ["Fall"],
            "gen_ed": ["Natural Science"],
            "tags": [],
        },
        "CHEM 112L": {
            "title": "Introductory Chemistry II",
            "credits": 1.25,
            "prereqs": ["CHEM 111L"],
            "offered": ["Spring"],
            "gen_ed": ["Natural Science"],
            "tags": [],
        },
        "CHEM 211L": {
            "title": "Organic Chemistry I",
            "credits": 1.25,
            "prereqs": ["CHEM 112L"],
            "offered": ["Fall"],
            "gen_ed": ["Natural Science"],
            "tags": [],
        },
        "CHEM 212L": {
            "title": "Organic Chemistry II",
            "credits": 1.25,
            "prereqs": ["CHEM 211L"],
            "offered": ["Spring"],
            "gen_ed": ["Natural Science"],
            "tags": [],
        },
        "CHEM 230L": {
            "title": "Analytical Chemistry",
            "credits": 1.0,
            "prereqs": ["CHEM 112L"],
            "offered": ["Fall"],
            "gen_ed": ["Natural Science"],
            "tags": [],
        },
        "CHEM 309L": {
            "title": "Physical Chemistry I",
            "credits": 1.0,
            "prereqs": ["CHEM 112L", "PHYS 141L", "MATH 132"],
            "offered": ["Fall"],
            "gen_ed": ["Natural Science"],
            "tags": [],
        },
        "CHEM 310": {
            "title": "Physical Chemistry II",
            "credits": 1.0,
            "prereqs": ["CHEM 309L"],
            "offered": ["Spring"],
            "gen_ed": ["Natural Science"],
            "tags": [],
        },
        "CHEM 316L": {
            "title": "Physical Biochemistry",
            "credits": 1.0,
            "prereqs": ["CHEM 212L", "CHEM 309L"],
            "offered": ["Alternate Years"],
            "gen_ed": ["Natural Science"],
            "tags": [],
        },
        "CHEM 404": {
            "title": "Advanced Inorganic Chemistry",
            "credits": 1.0,
            "prereqs": ["CHEM 310"],
            "offered": ["Alternate Years"],
            "gen_ed": ["Natural Science"],
            "tags": [],
        },
        "CHEM 410": {
            "title": "Advanced Biochemistry",
            "credits": 1.0,
            "prereqs": ["CHEM 317L"],  # Biochemistry in BIOL
            "offered": ["Alternate Years"],
            "gen_ed": ["Natural Science"],
            "tags": [],
        },
    },
    "Computer Science": {
        "CPSC 115L": {
            "title": "Introduction to Computer Science",
            "credits": 1.0,
            "prereqs": [],
            "offered": ["Fall", "Spring"],
            "gen_ed": ["Numerical Reasoning"],
            "tags": [],
        },
        "CPSC 203": {
            "title": "Mathematical Foundations of Computing",
            "credits": 1.0,
            "prereqs": ["CPSC 115L"],
            "offered": ["Spring"],
            "gen_ed": ["Numerical Reasoning"],
            "tags": [],
        },
        "CPSC 215L": {
            "title": "Data Structures and Algorithms",
            "credits": 1.0,
            "prereqs": ["CPSC 115L"],
            "offered": ["Fall"],
            "gen_ed": ["Numerical Reasoning"],
            "tags": [],
        },
        "CPSC 219": {
            "title": "Theory of Computation",
            "credits": 1.0,
            "prereqs": ["CPSC 203"],
            "offered": ["Spring"],
            "gen_ed": ["Numerical Reasoning"],
            "tags": [],
        },
        "CPSC 275L": {
            "title": "Introduction to Computer Systems",
            "credits": 1.0,
            "prereqs": ["CPSC 115L", "CPSC 203"],
            "offered": ["Spring"],
            "gen_ed": ["Natural Science"],
            "tags": [],
        },
        "CPSC 310": {
            "title": "Software Design",
            "credits": 1.0,
            "prereqs": ["CPSC 215L"],
            "offered": ["Fall"],
            "gen_ed": [],
            "tags": [],
        },
        "CPSC 315": {
            "title": "Systems Software",
            "credits": 1.0,
            "prereqs": ["CPSC 275L"],
            "offered": ["Alternate Years"],
            "gen_ed": [],
            "tags": [],
        },
        "CPSC 320": {
            "title": "Analysis of Algorithms",
            "credits": 1.0,
            "prereqs": ["CPSC 215L", "MATH 205"],
            "offered": ["Spring"],
            "gen_ed": [],
            "tags": [],
        },
        "CPSC 333": {
            "title": "Computer Networks",
            "credits": 1.0,
            "prereqs": ["CPSC 315"],
            "offered": ["Alternate Years"],
            "gen_ed": [],
            "tags": [],
        },
        "CPSC 352": {
            "title": "Artificial Intelligence",
            "credits": 1.0,
            "prereqs": ["CPSC 215L"],
            "offered": ["Alternate Years"],
            "gen_ed": [],
            "tags": [],
        },
        "CPSC 360": {
            "title": "Deep Learning",
            "credits": 1.0,
            "prereqs": ["CPSC 215L", "MATH 207"],
            "offered": ["Alternate Years"],
            "gen_ed": [],
            "tags": [],
        },
        "CPSC 372": {
            "title": "Database Fundamentals",
            "credits": 1.0,
            "prereqs": ["CPSC 215L"],
            "offered": ["Alternate Years"],
            "gen_ed": [],
            "tags": [],
        },
        "CPSC 375": {
            "title": "High-Performance Computing",
            "credits": 1.0,
            "prereqs": ["CPSC 215L"],
            "offered": ["Alternate Years"],
            "gen_ed": [],
            "tags": [],
        },
    },
    "Economics": {
        "ECON 101": {
            "title": "Principles of Microeconomics",
            "credits": 1.0,
            "prereqs": [],
            "offered": ["Fall"],
            "gen_ed": ["Social Science"],
            "tags": [],
        },
        "ECON 102": {
            "title": "Principles of Macroeconomics",
            "credits": 1.0,
            "prereqs": [],
            "offered": ["Spring"],
            "gen_ed": ["Social Science"],
            "tags": [],
        },
        "ECON 218": {
            "title": "Statistical Methods in Economics",
            "credits": 1.0,
            "prereqs": ["ECON 101", "MATH 107"],
            "offered": ["Fall", "Spring"],
            "gen_ed": ["Numerical Reasoning"],
            "tags": [],
        },
        "ECON 301": {
            "title": "Intermediate Microeconomic Theory",
            "credits": 1.0,
            "prereqs": ["ECON 101", "MATH 131"],
            "offered": ["Fall"],
            "gen_ed": [],
            "tags": [],
        },
        "ECON 302": {
            "title": "Intermediate Macroeconomic Theory",
            "credits": 1.0,
            "prereqs": ["ECON 102", "MATH 131"],
            "offered": ["Spring"],
            "gen_ed": [],
            "tags": [],
        },
        "ECON 312": {
            "title": "Mathematical Economics",
            "credits": 1.0,
            "prereqs": ["ECON 301", "MATH 228"],
            "offered": ["Alternate Years"],
            "gen_ed": [],
            "tags": [],
        },
        "ECON 316": {
            "title": "Money and Banking",
            "credits": 1.0,
            "prereqs": ["ECON 102"],
            "offered": ["Alternate Years"],
            "gen_ed": [],
            "tags": [],
        },
        "ECON 318": {
            "title": "Introduction to Econometrics",
            "credits": 1.0,
            "prereqs": ["ECON 218"],
            "offered": ["Spring"],
            "gen_ed": ["Numerical Reasoning"],
            "tags": [],
        },
        "ECON 321": {
            "title": "International Trade",
            "credits": 1.0,
            "prereqs": ["ECON 301"],
            "offered": ["Alternate Years"],
            "gen_ed": [],
            "tags": [],
        },
        "ECON 323": {
            "title": "Public Economics",
            "credits": 1.0,
            "prereqs": ["ECON 301"],
            "offered": ["Alternate Years"],
            "gen_ed": [],
            "tags": [],
        },
        "ECON 351": {
            "title": "Development Economics",
            "credits": 1.0,
            "prereqs": ["ECON 301"],
            "offered": ["Alternate Years"],
            "gen_ed": [],
            "tags": [],
        },
        "ECON 398": {
            "title": "Senior Seminar in Economics",
            "credits": 1.0,
            "prereqs": ["Senior Standing"],
            "offered": ["Fall", "Spring"],
            "gen_ed": ["Writing Emphasis 2"],
            "tags": [],
        },
    },
    "English": {
        "ENGL 260": {
            "title": "Approaches to Literary Study",
            "credits": 1.0,
            "prereqs": [],
            "offered": ["Fall"],
            "gen_ed": ["Humanities", "Writing Emphasis 2"],
            "tags": [],
        },
        "ENGL 270": {
            "title": "Shakespeare",
            "credits": 1.0,
            "prereqs": [],
            "offered": ["Spring"],
            "gen_ed": ["Humanities"],
            "tags": [],
        },
        "ENGL 275": {
            "title": "American Literature to 1865",
            "credits": 1.0,
            "prereqs": [],
            "offered": ["Alternate Years"],
            "gen_ed": ["Humanities"],
            "tags": [],
        },
        "ENGL 290": {
            "title": "Creative Writing: Poetry",
            "credits": 1.0,
            "prereqs": [],
            "offered": ["Fall"],
            "gen_ed": [],
            "tags": [],
        },
        "ENGL 319": {
            "title": "Literary Theory and Criticism",
            "credits": 1.0,
            "prereqs": ["ENGL 260"],
            "offered": ["Alternate Years"],
            "gen_ed": ["Humanities"],
            "tags": [],
        },
        "ENGL 401": {
            "title": "Senior Seminar in English",
            "credits": 1.0,
            "prereqs": ["Senior Standing"],
            "offered": ["Spring"],
            "gen_ed": ["Writing Emphasis 2"],
            "tags": [],
        },
    },
    "Engineering": {
        "ENGR 116": {
            "title": "Introduction to Engineering Design",
            "credits": 1.0,
            "prereqs": [],
            "offered": ["Fall"],
            "gen_ed": ["Natural Science"],
            "tags": [],
        },
        "ENGR 212L": {
            "title": "Linear Circuit Theory",
            "credits": 1.0,
            "prereqs": ["PHYS 141L", "MATH 132"],
            "offered": ["Spring"],
            "gen_ed": ["Natural Science"],
            "tags": [],
        },
        "ENGR 225": {
            "title": "Mechanics I (Statics)",
            "credits": 1.0,
            "prereqs": ["PHYS 141L", "MATH 131"],
            "offered": ["Fall"],
            "gen_ed": ["Natural Science"],
            "tags": [],
        },
        "ENGR 226": {
            "title": "Mechanics II (Dynamics)",
            "credits": 1.0,
            "prereqs": ["ENGR 225"],
            "offered": ["Spring"],
            "gen_ed": ["Natural Science"],
            "tags": [],
        },
        "ENGR 301L": {
            "title": "Signal Processing and Applications",
            "credits": 1.0,
            "prereqs": ["ENGR 212L", "MATH 234"],
            "offered": ["Fall"],
            "gen_ed": ["Natural Science"],
            "tags": [],
        },
        "ENGR 303L": {
            "title": "Analog and Digital Communication",
            "credits": 1.0,
            "prereqs": ["ENGR 301L"],
            "offered": ["Spring"],
            "gen_ed": ["Natural Science"],
            "tags": [],
        },
        "ENGR 306": {
            "title": "Introduction to Machine Learning",
            "credits": 1.0,
            "prereqs": ["CPSC 215L", "MATH 207"],
            "offered": ["Alternate Years"],
            "gen_ed": ["Numerical Reasoning"],
            "tags": ["Cross-listed Data Science"],
        },
        "ENGR 312": {
            "title": "Automatic Control Systems",
            "credits": 1.0,
            "prereqs": ["ENGR 212L", "MATH 234"],
            "offered": ["Spring"],
            "gen_ed": ["Natural Science"],
            "tags": [],
        },
        "ENGR 337": {
            "title": "Thermodynamics",
            "credits": 1.0,
            "prereqs": ["CHEM 112L", "MATH 131"],
            "offered": ["Fall"],
            "gen_ed": ["Natural Science"],
            "tags": [],
        },
        "ENGR 346L": {
            "title": "Computational Neuroscience",
            "credits": 1.0,
            "prereqs": ["ENGR 212L", "NESC 201"],
            "offered": ["Alternate Years"],
            "gen_ed": ["Natural Science"],
            "tags": ["Neuroscience"],
        },
        "ENGR 362L": {
            "title": "Fluid Dynamics",
            "credits": 1.0,
            "prereqs": ["ENGR 225", "MATH 234"],
            "offered": ["Spring"],
            "gen_ed": ["Natural Science"],
            "tags": [],
        },
        "ENGR 401": {
            "title": "Senior Design Project I",
            "credits": 0.5,
            "prereqs": ["Senior Standing"],
            "offered": ["Fall"],
            "gen_ed": [],
            "tags": [],
        },
        "ENGR 402": {
            "title": "Senior Design Project II",
            "credits": 0.5,
            "prereqs": ["ENGR 401"],
            "offered": ["Spring"],
            "gen_ed": [],
            "tags": [],
        },
    },
    "Environmental Science": {
        "ENVS 149": {
            "title": "Introduction to Environmental Science",
            "credits": 1.0,
            "prereqs": [],
            "offered": ["Fall"],
            "gen_ed": ["Natural Science"],
            "tags": [],
        },
        "ENVS 204": {
            "title": "Climate Change and Human Health",
            "credits": 1.0,
            "prereqs": [],
            "offered": ["Spring"],
            "gen_ed": ["Natural Science"],
            "tags": [],
        },
        "ENVS 286": {
            "title": "Theory and Application of GIS",
            "credits": 1.0,
            "prereqs": [],
            "offered": ["Spring"],
            "gen_ed": ["Natural Science"],
            "tags": [],
        },
        "ENVS 305": {
            "title": "Environmental Policy",
            "credits": 1.0,
            "prereqs": [],
            "offered": ["Alternate Years"],
            "gen_ed": ["Social Science"],
            "tags": ["Cross-listed Public Policy & Law"],
        },
        "ENVS 401": {
            "title": "Environmental Science Senior Seminar",
            "credits": 1.0,
            "prereqs": ["Senior Standing"],
            "offered": ["Spring"],
            "gen_ed": ["Writing Emphasis 2"],
            "tags": [],
        },
    },
    "Film Studies": {
        "FILM 265": {
            "title": "Introduction to Film Studies",
            "credits": 1.0,
            "prereqs": [],
            "offered": ["Fall"],
            "gen_ed": ["Humanities"],
            "tags": ["Cross-listed English"],
        },
        "FILM 309": {
            "title": "Film Theory and Criticism",
            "credits": 1.0,
            "prereqs": ["FILM 265"],
            "offered": ["Alternate Years"],
            "gen_ed": ["Humanities"],
            "tags": [],
        },
        "FILM 321": {
            "title": "World Cinema",
            "credits": 1.0,
            "prereqs": ["FILM 265"],
            "offered": ["Alternate Years"],
            "gen_ed": ["Humanities"],
            "tags": [],
        },
        "FILM 355": {
            "title": "Advanced Filmmaking",
            "credits": 1.0,
            "prereqs": [],  # some production experience recommended
            "offered": ["Spring"],
            "gen_ed": [],
            "tags": [],
        },
        "FILM 401": {
            "title": "Senior Seminar in Film Studies",
            "credits": 1.0,
            "prereqs": ["Senior Standing"],
            "offered": ["Spring"],
            "gen_ed": ["Writing Emphasis 2"],
            "tags": [],
        },
    },
    "First Year Seminar": {
        "FYSM180": {
            "title": "Imagining Paris",
            "credits": 1.0,
            "prereqs": [],
            "offered": ["Fall"],
            "gen_ed": ["First-Year Seminar", "Writing Emphasis 1"],
            "tags": [],
        },
        "FYSM189": {
            "title": "The Global City",
            "credits": 1.0,
            "prereqs": [],
            "offered": ["Fall"],
            "gen_ed": ["First-Year Seminar", "Writing Emphasis 1", "Global Engagement"],
            "tags": [],
        },
        "FYSM193": {
            "title": "Science and Society",
            "credits": 1.0,
            "prereqs": [],
            "offered": ["Fall"],
            "gen_ed": ["First-Year Seminar", "Writing Emphasis 1"],
            "tags": [],
        },
    },
    "History": {
        "HIST 201": {
            "title": "Early America (to 1865)",
            "credits": 1.0,
            "prereqs": [],
            "offered": ["Fall"],
            "gen_ed": ["Humanities", "Global Engagement"],
            "tags": ["Cross-listed American Studies"],
        },
        "HIST 202": {
            "title": "Modern America (since 1865)",
            "credits": 1.0,
            "prereqs": [],
            "offered": ["Spring"],
            "gen_ed": ["Humanities"],
            "tags": [],
        },
        "HIST 233": {
            "title": "Whiteness as a Racial Category",
            "credits": 1.0,
            "prereqs": [],
            "offered": ["Fall"],
            "gen_ed": ["Humanities", "Global Engagement"],
            "tags": [],
        },
        "HIST 285": {
            "title": "Violence in U.S. History (1754–1900)",
            "credits": 1.0,
            "prereqs": [],
            "offered": ["Spring"],
            "gen_ed": ["Humanities"],
            "tags": [],
        },
        "HIST 311": {
            "title": "Seminar: Critical Indigenous Histories",
            "credits": 1.0,
            "prereqs": ["One 200-level HIST"],
            "offered": ["Fall"],
            "gen_ed": ["Humanities", "Writing Emphasis 2"],
            "tags": [],
        },
        "HIST 315": {
            "title": "Seminar: Topics in European History",
            "credits": 1.0,
            "prereqs": ["One 200-level HIST"],
            "offered": ["Alternate Years"],
            "gen_ed": ["Humanities"],
            "tags": [],
        },
    },
    "International Studies": {
        "INTS 101": {
            "title": "Introduction to International Studies",
            "credits": 1.0,
            "prereqs": [],
            "offered": ["Fall"],
            "gen_ed": ["Global Engagement"],
            "tags": [],
        },
        "INTS 201": {
            "title": "Global Lives (Intermediate Core)",
            "credits": 1.0,
            "prereqs": ["INTS 101"],
            "offered": ["Spring"],
            "gen_ed": ["Global Engagement"],
            "tags": [],
        },
        "INTS 301": {
            "title": "Research Methods in International Studies",
            "credits": 1.0,
            "prereqs": ["INTS 101"],
            "offered": ["Alternate Years"],
            "gen_ed": ["Numerical Reasoning"],
            "tags": [],
        },
        "INTS 401": {
            "title": "Senior Seminar in International Studies",
            "credits": 1.0,
            "prereqs": ["Senior Standing"],
            "offered": ["Spring"],
            "gen_ed": ["Writing Emphasis 2"],
            "tags": [],
        },
    },
    "Mathematics": {
        "MATH 103": {
            "title": "Introduction to Sports Analytics",
            "credits": 1.0,
            "prereqs": [],  # placement exam recommended (no course prereq)
            "offered": ["Fall"],
            "gen_ed": ["Numerical Reasoning"],
            "tags": [],
        },
        "MATH 107": {
            "title": "Elements of Statistics",
            "credits": 1.0,
            "prereqs": [],  # QLIT 101 or placement
            "offered": ["Fall", "Spring"],
            "gen_ed": ["Numerical Reasoning"],
            "tags": [],
        },
        "MATH 114": {
            "title": "Decision Making in Politics (Mathematics of Voting)",
            "credits": 1.0,
            "prereqs": [],  # placement or QLIT 101
            "offered": ["Fall"],
            "gen_ed": ["Numerical Reasoning"],
            "tags": [],
        },
        "MATH 123": {
            "title": "Mathematical Gems",
            "credits": 1.0,
            "prereqs": ["QLIT 101"],  # quantitative literacy course
            "offered": ["Spring"],
            "gen_ed": ["Numerical Reasoning"],
            "tags": [],
        },
        "MATH 127": {
            "title": "Functions, Graphs, and Modeling",
            "credits": 1.0,
            "prereqs": [],  # placement or QLIT equivalent
            "offered": ["Fall", "Spring"],
            "gen_ed": ["Numerical Reasoning"],
            "tags": [],
        },
        "MATH 131": {
            "title": "Calculus I",
            "credits": 1.25,  # includes required workshop
            "prereqs": ["MATH 127"],  # or placement exam
            "offered": ["Fall", "Spring"],
            "gen_ed": ["Numerical Reasoning"],
            "tags": [],
        },
        "MATH 131L": {
            "title": "Calculus I Workshop",
            "credits": 0.25,
            "prereqs": ["MATH 131"],  # corequisite with Calc I
            "offered": ["Fall", "Spring"],
            "gen_ed": ["Numerical Reasoning"],
            "tags": [],
        },
        "MATH 132": {
            "title": "Calculus II",
            "credits": 1.25,  # includes workshop component
            "prereqs": ["MATH 131"],  # or appropriate exam score
            "offered": ["Spring"],
            "gen_ed": ["Numerical Reasoning"],
            "tags": [],
        },
        "MATH 205": {
            "title": "Abstraction and Argument",
            "credits": 1.0,
            "prereqs": ["MATH 132"],  # C+ or better in Calc II
            "offered": ["Fall", "Spring"],
            "gen_ed": ["Numerical Reasoning"],
            "tags": ["Writing Emphasis 2"],  # writing intensive Part II requirement
        },
        "MATH 207": {
            "title": "Statistical Data Analysis",
            "credits": 1.0,
            "prereqs": [
                "MATH 107"
            ],  # or MATH 127 and placement:contentReference[oaicite:3]{index=3}
            "offered": ["Fall", "Spring"],
            "gen_ed": ["Numerical Reasoning"],
            "tags": [],
        },
        "MATH 209": {
            "title": "Stochastic Processes",
            "credits": 1.0,
            "prereqs": ["MATH 132"],
            "offered": ["Alternate Years"],
            "gen_ed": ["Numerical Reasoning"],
            "tags": [],
        },
        "MATH 214": {
            "title": "Introduction to Combinatorics",
            "credits": 1.0,
            "prereqs": ["MATH 132"],
            "offered": ["Alternate Years"],
            "gen_ed": ["Numerical Reasoning"],
            "tags": [],
        },
        "MATH 228": {
            "title": "Linear Algebra (proof-based)",
            "credits": 1.0,
            "prereqs": ["MATH 132"],
            "offered": ["Fall", "Spring"],
            "gen_ed": ["Numerical Reasoning"],
            "tags": [],
        },
        "MATH 229": {
            "title": "Applied Linear Algebra",
            "credits": 1.0,
            "prereqs": ["MATH 132"],
            "offered": ["Fall", "Spring"],
            "gen_ed": ["Numerical Reasoning"],
            "tags": [],
        },
        "MATH 231": {
            "title": "Calculus III: Multivariable Calculus",
            "credits": 1.25,
            "prereqs": ["MATH 132"],
            "offered": ["Fall"],
            "gen_ed": ["Numerical Reasoning"],
            "tags": [],
        },
        "MATH 234": {
            "title": "Differential Equations",
            "credits": 1.0,
            "prereqs": ["MATH 231"],
            "offered": ["Spring"],
            "gen_ed": ["Numerical Reasoning"],
            "tags": [],
        },
        "MATH 237": {
            "title": "Topics in Number Theory",
            "credits": 1.0,
            "prereqs": ["MATH 132"],
            "offered": ["Alternate Years"],
            "gen_ed": ["Numerical Reasoning"],
            "tags": [],
        },
        "MATH 252": {
            "title": "Introduction to Mathematical Modeling I",
            "credits": 1.0,
            "prereqs": ["MATH 131"],
            "offered": ["Alternate Years"],
            "gen_ed": ["Numerical Reasoning"],
            "tags": [],
        },
        "MATH 254": {
            "title": "Introduction to Mathematical Modeling II",
            "credits": 1.0,
            "prereqs": ["MATH 252"],
            "offered": ["Alternate Years"],
            "gen_ed": ["Numerical Reasoning"],
            "tags": [],
        },
        "MATH 253": {
            "title": "Number Theory and Applications",
            "credits": 1.0,
            "prereqs": ["MATH 132"],
            "offered": ["Alternate Years"],
            "gen_ed": ["Numerical Reasoning"],
            "tags": [],
        },
        "MATH 305": {
            "title": "Probability",
            "credits": 1.0,
            "prereqs": ["MATH 207"],
            "offered": ["Alternate Years"],
            "gen_ed": ["Numerical Reasoning"],
            "tags": [],
        },
        "MATH 306": {
            "title": "Mathematical Statistics",
            "credits": 1.0,
            "prereqs": ["MATH 305"],
            "offered": ["Alternate Years"],
            "gen_ed": ["Numerical Reasoning"],
            "tags": [],
        },
        "MATH 307": {
            "title": "Abstract Algebra",
            "credits": 1.0,
            "prereqs": ["MATH 205"],
            "offered": ["Fall"],
            "gen_ed": ["Numerical Reasoning", "Writing Emphasis 2"],
            "tags": [],
        },
        "MATH 308": {
            "title": "Topics in Advanced Algebra",
            "credits": 1.0,
            "prereqs": ["MATH 307"],
            "offered": ["Alternate Years"],
            "gen_ed": ["Numerical Reasoning"],
            "tags": [],
        },
        "MATH 309": {
            "title": "Numerical Analysis",
            "credits": 1.0,
            "prereqs": ["CPSC 115L", "MATH 228"],  # CS intro and Linear Algebra
            "offered": ["Spring"],
            "gen_ed": ["Numerical Reasoning"],
            "tags": ["Applied Math concentration"],
        },
        "MATH 314": {
            "title": "Combinatorics and Computing",
            "credits": 1.0,
            "prereqs": ["MATH 205"],
            "offered": ["Alternate Years"],
            "gen_ed": ["Numerical Reasoning"],
            "tags": [],
        },
        "MATH 316": {
            "title": "Topics in Applied Mathematics",
            "credits": 1.0,
            "prereqs": ["MATH 234"],  # after Differential Equations
            "offered": ["Alternate Years"],
            "gen_ed": ["Numerical Reasoning"],
            "tags": ["Applied Math concentration"],
        },
        "MATH 318": {
            "title": "Advanced Topics in Mathematics",
            "credits": 1.0,
            "prereqs": [],  # varies by topic
            "offered": ["Alternate Years"],
            "gen_ed": ["Numerical Reasoning"],
            "tags": [],
        },
        "MATH 326": {
            "title": "Graph Theory with Applications",
            "credits": 1.0,
            "prereqs": ["MATH 205"],
            "offered": ["Alternate Years"],
            "gen_ed": ["Numerical Reasoning"],
            "tags": ["Applied Math concentration"],
        },
        "MATH 332": {
            "title": "Analysis II (Real Analysis continuation)",
            "credits": 1.0,
            "prereqs": ["MATH 331"],
            "offered": ["Alternate Years"],
            "gen_ed": ["Numerical Reasoning"],
            "tags": [],
        },
        "MATH 334": {
            "title": "Differential Equations II / Dynamical Systems",
            "credits": 1.0,
            "prereqs": ["MATH 234"],
            "offered": ["Alternate Years"],
            "gen_ed": ["Numerical Reasoning"],
            "tags": ["Applied Math concentration"],
        },
        "MATH 341": {
            "title": "Complex Analysis",
            "credits": 1.0,
            "prereqs": ["MATH 331"],  # Analysis I
            "offered": ["Alternate Years"],
            "gen_ed": ["Numerical Reasoning"],
            "tags": [],
        },
        "MATH 400": {
            "title": "Senior Seminar in Mathematics",
            "credits": 1.0,
            "prereqs": ["Senior Standing"],
            "offered": ["Fall", "Spring"],
            "gen_ed": [],
            "tags": [],
        },
        "MATH 406": {
            "title": "Reading and Research Seminar",
            "credits": 1.0,
            "prereqs": ["Instructor Permission"],
            "offered": ["Spring"],
            "gen_ed": [],
            "tags": [],
        },
    },
    "Music": {
        "MUSC 101": {
            "title": "Music Theory I",
            "credits": 1.0,
            "prereqs": [],
            "offered": ["Fall"],
            "gen_ed": ["Arts"],
            "tags": [],
        },
        "MUSC 105": {
            "title": "Introduction to World Music",
            "credits": 1.0,
            "prereqs": [],
            "offered": ["Spring"],
            "gen_ed": ["Global Engagement"],
            "tags": [],
        },
        "MUSC 201": {
            "title": "History of Western Music I",
            "credits": 1.0,
            "prereqs": [],
            "offered": ["Fall"],
            "gen_ed": ["Humanities"],
            "tags": [],
        },
        "MUSC 227": {
            "title": "Jazz: A Multicultural History",
            "credits": 1.0,
            "prereqs": [],
            "offered": ["Alternate Years"],
            "gen_ed": ["Arts"],
            "tags": [],
        },
        "MUSC 312": {
            "title": "Composition Workshop",
            "credits": 1.0,
            "prereqs": ["MUSC 101"],
            "offered": ["Spring"],
            "gen_ed": ["Arts"],
            "tags": [],
        },
        "MUSC 407": {
            "title": "Senior Recital",
            "credits": 0.5,
            "prereqs": ["Senior Standing"],
            "offered": ["Spring"],
            "gen_ed": [],
            "tags": [],
        },
    },
    "Neuroscience": {
        "NESC 201": {
            "title": "Principles of Neuroscience",
            "credits": 1.0,
            "prereqs": ["BIOL 182L", "PSYC 101"],
            "offered": ["Spring"],
            "gen_ed": ["Natural Science"],
            "tags": [],
        },
        "NESC 220": {
            "title": "Statistics for Life Sciences",
            "credits": 1.0,
            "prereqs": ["MATH 107"],
            "offered": ["Fall"],
            "gen_ed": ["Numerical Reasoning"],
            "tags": [],
        },
        "NESC 301": {
            "title": "Neuropharmacology",
            "credits": 1.0,
            "prereqs": ["PSYC 261", "BIOL 183L"],
            "offered": ["Alternate Years"],
            "gen_ed": ["Natural Science"],
            "tags": [],
        },
        "NESC 388": {
            "title": "Current Issues in Neuroscience",
            "credits": 1.0,
            "prereqs": ["NESC 201"],
            "offered": ["Fall"],
            "gen_ed": ["Natural Science"],
            "tags": [],
        },
        "NESC 402": {
            "title": "Senior Seminar in Neuroscience",
            "credits": 1.0,
            "prereqs": ["Senior Standing"],
            "offered": ["Spring"],
            "gen_ed": ["Natural Science", "Writing Emphasis 2"],
            "tags": [],
        },
        "NESC 425": {
            "title": "Neuroscience Research Lab",
            "credits": 1.0,
            "prereqs": ["NESC 201"],
            "offered": ["Fall", "Spring"],
            "gen_ed": ["Natural Science"],
            "tags": [],
        },
    },
    "Philosophy": {
        "PHIL 101": {
            "title": "Introduction to Philosophy",
            "credits": 1.0,
            "prereqs": [],
            "offered": ["Fall", "Spring"],
            "gen_ed": ["Humanities"],
            "tags": [],
        },
        "PHIL 103": {
            "title": "Introduction to Ethics",
            "credits": 1.0,
            "prereqs": [],
            "offered": ["Fall"],
            "gen_ed": ["Humanities"],
            "tags": [],
        },
        "PHIL 205": {
            "title": "Symbolic Logic",
            "credits": 1.0,
            "prereqs": [],
            "offered": ["Spring"],
            "gen_ed": ["Numerical Reasoning"],
            "tags": [],
        },
        "PHIL 246": {
            "title": "Philosophy of Science",
            "credits": 1.0,
            "prereqs": [],
            "offered": ["Alternate Years"],
            "gen_ed": ["Humanities"],
            "tags": [],
        },
        "PHIL 374": {
            "title": "Minds and Brains",
            "credits": 1.0,
            "prereqs": [],
            "offered": ["Alternate Years"],
            "gen_ed": ["Humanities"],
            "tags": ["Cross-listed Neuroscience"],
        },
        "PHIL 390": {
            "title": "Seminar in Philosophy",
            "credits": 1.0,
            "prereqs": ["One 200-level PHIL"],
            "offered": ["Spring"],
            "gen_ed": ["Writing Emphasis 2"],
            "tags": [],
        },
    },
    "Physics": {
        "PHYS 141L": {
            "title": "Physics I: Mechanics",
            "credits": 1.25,
            "prereqs": ["MATH 131"],
            "offered": ["Fall"],
            "gen_ed": ["Natural Science"],
            "tags": [],
        },
        "PHYS 142L": {
            "title": "Physics II: Electricity & Magnetism",
            "credits": 1.25,
            "prereqs": ["PHYS 141L", "MATH 132"],
            "offered": ["Spring"],
            "gen_ed": ["Natural Science"],
            "tags": [],
        },
        "PHYS 232L": {
            "title": "Physics III: Optics and Modern Physics",
            "credits": 1.0,
            "prereqs": ["PHYS 142L"],
            "offered": ["Fall"],
            "gen_ed": ["Natural Science"],
            "tags": [],
        },
        "PHYS 300": {
            "title": "Mathematical Methods of Physics",
            "credits": 1.0,
            "prereqs": ["PHYS 232L", "MATH 234"],
            "offered": ["Spring"],
            "gen_ed": ["Natural Science"],
            "tags": [],
        },
        "PHYS 301": {
            "title": "Classical Mechanics",
            "credits": 1.0,
            "prereqs": ["PHYS 232L", "MATH 234"],
            "offered": ["Fall"],
            "gen_ed": ["Natural Science"],
            "tags": [],
        },
        "PHYS 302": {
            "title": "Electrodynamics",
            "credits": 1.0,
            "prereqs": ["PHYS 232L", "MATH 234"],
            "offered": ["Spring"],
            "gen_ed": ["Natural Science"],
            "tags": [],
        },
        "PHYS 304": {
            "title": "Statistical and Thermal Physics",
            "credits": 1.0,
            "prereqs": ["PHYS 232L", "MATH 234"],
            "offered": ["Alternate Years"],
            "gen_ed": ["Natural Science"],
            "tags": [],
        },
        "PHYS 313": {
            "title": "Quantum Mechanics",
            "credits": 1.0,
            "prereqs": ["PHYS 232L", "MATH 234"],
            "offered": ["Spring"],
            "gen_ed": ["Natural Science"],
            "tags": [],
        },
        "PHYS 315": {
            "title": "Advanced Laboratory",
            "credits": 1.0,
            "prereqs": ["PHYS 232L"],
            "offered": ["Alternate Years"],
            "gen_ed": ["Natural Science", "Writing Emphasis 2"],
            "tags": [],
        },
    },
    "Political Science": {
        "POLS 102": {
            "title": "American National Government",
            "credits": 1.0,
            "prereqs": [],
            "offered": ["Fall"],
            "gen_ed": ["Social Science"],
            "tags": [],
        },
        "POLS 103": {
            "title": "Introduction to International Relations",
            "credits": 1.0,
            "prereqs": [],
            "offered": ["Fall"],
            "gen_ed": ["Social Science"],
            "tags": [],
        },
        "POLS 104": {
            "title": "Comparative Politics",
            "credits": 1.0,
            "prereqs": [],
            "offered": ["Spring"],
            "gen_ed": ["Social Science"],
            "tags": [],
        },
        "POLS 105": {
            "title": "Introduction to Political Theory",
            "credits": 1.0,
            "prereqs": [],
            "offered": ["Spring"],
            "gen_ed": ["Humanities"],
            "tags": [],
        },
        "POLS 242": {
            "title": "Research Methods in Political Science",
            "credits": 1.0,
            "prereqs": ["POLS 102"],
            "offered": ["Fall"],
            "gen_ed": ["Numerical Reasoning"],
            "tags": [],
        },
        "POLS 310": {
            "title": "Constitutional Law",
            "credits": 1.0,
            "prereqs": ["POLS 102"],
            "offered": ["Alternate Years"],
            "gen_ed": [],
            "tags": ["Cross-listed Public Policy & Law"],
        },
        "POLS 314": {
            "title": "Comparative Urban Development",
            "credits": 1.0,
            "prereqs": ["POLS 104"],
            "offered": ["Alternate Years"],
            "gen_ed": ["Social Science"],
            "tags": ["Cross-listed Urban Studies"],
        },
        "POLS 316": {
            "title": "International Law",
            "credits": 1.0,
            "prereqs": ["POLS 103"],
            "offered": ["Alternate Years"],
            "gen_ed": [],
            "tags": [],
        },
        "POLS 355": {
            "title": "Urban Politics",
            "credits": 1.0,
            "prereqs": ["POLS 102"],
            "offered": ["Alternate Years"],
            "gen_ed": [],
            "tags": ["Cross-listed Urban Studies"],
        },
        "POLS 363": {
            "title": "Global Justice",
            "credits": 1.0,
            "prereqs": ["POLS 105"],
            "offered": ["Alternate Years"],
            "gen_ed": ["Humanities"],
            "tags": [],
        },
        "POLS 401": {
            "title": "Seminar in American Politics",
            "credits": 1.0,
            "prereqs": ["Senior Standing"],
            "offered": ["Fall"],
            "gen_ed": ["Writing Emphasis 2"],
            "tags": [],
        },
    },
    "Portuguese": {
        "PORT 101": {
            "title": "Elementary Portuguese I",
            "credits": 1.0,
            "prereqs": [],
            "offered": ["Fall"],
            "gen_ed": ["Second Language"],
            "tags": [],
        },
        "PORT 102": {
            "title": "Elementary Portuguese II",
            "credits": 1.0,
            "prereqs": ["PORT 101"],
            "offered": ["Spring"],
            "gen_ed": ["Second Language"],
            "tags": [],
        },
        "PORT 201": {
            "title": "Intermediate Portuguese I",
            "credits": 1.0,
            "prereqs": ["PORT 102"],
            "offered": ["Fall"],
            "gen_ed": ["Second Language"],
            "tags": [],
        },
        "PORT 202": {
            "title": "Intermediate Portuguese II",
            "credits": 1.0,
            "prereqs": ["PORT 201"],
            "offered": ["Spring"],
            "gen_ed": ["Second Language"],
            "tags": [],
        },
    },
    "Psychology": {
        "PSYC 101": {
            "title": "Introduction to Psychological Science",
            "credits": 1.0,
            "prereqs": [],
            "offered": ["Spring"],
            "gen_ed": ["Social Science"],
            "tags": [],
        },
        "PSYC 206": {
            "title": "Environmental Psychology and Sustainability",
            "credits": 1.0,
            "prereqs": ["PSYC 101"],
            "offered": ["Fall"],
            "gen_ed": ["Social Science"],
            "tags": [],
        },
        "PSYC 212": {
            "title": "Brain Health: Landscape Planning & Education",
            "credits": 1.0,
            "prereqs": ["PSYC 101"],
            "offered": ["Fall"],
            "gen_ed": ["Natural Science"],
            "tags": [],
        },
        "PSYC 221L": {
            "title": "Research Design and Analysis",
            "credits": 1.0,
            "prereqs": ["PSYC 101"],
            "offered": ["Fall", "Spring"],
            "gen_ed": ["Numerical Reasoning"],
            "tags": [],
        },
        "PSYC 226": {
            "title": "Social Psychology",
            "credits": 1.0,
            "prereqs": ["PSYC 101"],
            "offered": ["Fall"],
            "gen_ed": ["Social Science"],
            "tags": [],
        },
        "PSYC 226L": {
            "title": "Social Psychology Lab",
            "credits": 0.25,
            "prereqs": ["PSYC 226"],
            "offered": ["Fall"],
            "gen_ed": ["Natural Science"],
            "tags": [],
        },
        "PSYC 237": {
            "title": "Health Psychology",
            "credits": 1.0,
            "prereqs": ["PSYC 101"],
            "offered": ["Spring"],
            "gen_ed": ["Social Science"],
            "tags": [],
        },
        "PSYC 255": {
            "title": "Cognitive Psychology",
            "credits": 1.0,
            "prereqs": ["PSYC 101"],
            "offered": ["Spring"],
            "gen_ed": ["Social Science"],
            "tags": [],
        },
        "PSYC 255L": {
            "title": "Cognitive Psychology Lab",
            "credits": 0.25,
            "prereqs": ["PSYC 255"],
            "offered": ["Spring"],
            "gen_ed": ["Natural Science"],
            "tags": [],
        },
        "PSYC 261": {
            "title": "Brain and Behavior",
            "credits": 1.0,
            "prereqs": ["PSYC 101", "BIOL 140"],
            "offered": ["Fall", "Spring"],
            "gen_ed": ["Natural Science"],
            "tags": ["Neuroscience core"],
        },
        "PSYC 270": {
            "title": "Clinical Psychology",
            "credits": 1.0,
            "prereqs": ["PSYC 101"],
            "offered": ["Spring"],
            "gen_ed": ["Social Science"],
            "tags": [],
        },
        "PSYC 273": {
            "title": "Psychopathology (Abnormal Psychology)",
            "credits": 1.0,
            "prereqs": ["PSYC 101"],
            "offered": ["Fall"],
            "gen_ed": ["Social Science", "Writing Emphasis 2"],
            "tags": [],
        },
        "PSYC 293L": {
            "title": "Sensation and Perception with Lab",
            "credits": 1.0,
            "prereqs": ["PSYC 101"],
            "offered": ["Spring"],
            "gen_ed": ["Natural Science"],
            "tags": [],
        },
        "PSYC 302": {
            "title": "Behavioral Neuroscience",
            "credits": 1.0,
            "prereqs": ["PSYC 261"],
            "offered": ["Fall"],
            "gen_ed": ["Natural Science"],
            "tags": ["Neuroscience"],
        },
        "PSYC 320": {
            "title": "Neuroscience Across the Lifespan",
            "credits": 1.0,
            "prereqs": ["PSYC 261"],
            "offered": ["Spring"],
            "gen_ed": ["Natural Science"],
            "tags": ["Neuroscience"],
        },
        "PSYC 332L": {
            "title": "Psychological Assessment (Lab)",
            "credits": 1.0,
            "prereqs": ["PSYC 221L"],
            "offered": ["Alternate Years"],
            "gen_ed": ["Social Science"],
            "tags": [],
        },
        "PSYC 339": {
            "title": "Developmental Psychopathology",
            "credits": 1.0,
            "prereqs": ["PSYC 273"],
            "offered": ["Alternate Years"],
            "gen_ed": ["Social Science"],
            "tags": [],
        },
        "PSYC 365": {
            "title": "Cognitive and Social Neuroscience",
            "credits": 1.0,
            "prereqs": ["PSYC 261"],
            "offered": ["Alternate Years"],
            "gen_ed": ["Natural Science"],
            "tags": ["Neuroscience"],
        },
        "PSYC 375": {
            "title": "Special Topics in Psychology",
            "credits": 1.0,
            "prereqs": [],
            "offered": ["Irregular"],
            "gen_ed": [],
            "tags": [],
        },
        "PSYC 391": {
            "title": "Psychology of Language",
            "credits": 1.0,
            "prereqs": ["PSYC 255"],
            "offered": ["Alternate Years"],
            "gen_ed": ["Social Science"],
            "tags": [],
        },
        "PSYC 392": {
            "title": "Human Neuropsychology",
            "credits": 1.0,
            "prereqs": ["PSYC 261"],
            "offered": ["Alternate Years"],
            "gen_ed": ["Natural Science"],
            "tags": ["Neuroscience"],
        },
        "PSYC 498": {
            "title": "Senior Thesis I",
            "credits": 0.5,
            "prereqs": ["Instructor Permission"],
            "offered": ["Fall"],
            "gen_ed": [],
            "tags": [],
        },
        "PSYC 499": {
            "title": "Senior Thesis II",
            "credits": 0.5,
            "prereqs": ["PSYC 498"],
            "offered": ["Spring"],
            "gen_ed": [],
            "tags": [],
        },
    },
    "Public Policy & Law": {
        "PBPL 201": {
            "title": "Introduction to American Public Policy",
            "credits": 1.0,
            "prereqs": [],
            "offered": ["Fall"],
            "gen_ed": ["Social Science"],
            "tags": [],
        },
        "PBPL 202": {
            "title": "Law, Argument, and Public Policy",
            "credits": 1.0,
            "prereqs": [],
            "offered": ["Spring"],
            "gen_ed": ["Social Science"],
            "tags": [],
        },
        "PBPL 220": {
            "title": "Research and Evaluation",
            "credits": 1.0,
            "prereqs": ["PBPL 201"],
            "offered": ["Spring"],
            "gen_ed": ["Numerical Reasoning"],
            "tags": [],
        },
        "PBPL 331": {
            "title": "Constitutional Law II: Civil Rights & Liberties",
            "credits": 1.0,
            "prereqs": ["POLS 102"],
            "offered": ["Alternate Years"],
            "gen_ed": [],
            "tags": ["Cross-listed Political Science"],
        },
        "PBPL 414": {
            "title": "Segregation and Public Policy",
            "credits": 1.0,
            "prereqs": ["PBPL 202"],
            "offered": ["Spring"],
            "gen_ed": ["Social Science"],
            "tags": [],
        },
        "PBPL 497": {
            "title": "Senior Thesis",
            "credits": 1.0,
            "prereqs": ["Senior Standing"],
            "offered": ["Fall"],
            "gen_ed": [],
            "tags": [],
        },
    },
    "Quantitative Literacy": {
        "QLIT101": {
            "title": "Quantitative Literacy",
            "credits": 1.0,
            "prereqs": [],
            "offered": ["Fall", "Spring"],
            "gen_ed": ["Numerical & Symbolic Reasoning"],
            "tags": [],
        }
        # (Quantitative literacy is a foundational requirement; QLIT 101 is the primary course)
    },
    "Religious Studies": {
        "RELG101": {
            "title": "Introduction to Religion",
            "credits": 1.0,
            "prereqs": [],
            "offered": ["Fall"],
            "gen_ed": ["Humanities"],
            "tags": [],
        },
        "RELG109": {
            "title": "World Religions",
            "credits": 1.0,
            "prereqs": [],
            "offered": ["Spring"],
            "gen_ed": ["Humanities", "Global Engagement"],
            "tags": [],
        },
        "RELG211": {
            "title": "Hebrew Bible",
            "credits": 1.0,
            "prereqs": [],
            "offered": ["Alternate Years"],
            "gen_ed": ["Humanities"],
            "tags": [],
        },
        "RELG212": {
            "title": "New Testament",
            "credits": 1.0,
            "prereqs": [],
            "offered": ["Alternate Years"],
            "gen_ed": ["Humanities"],
            "tags": [],
        },
        "RELG260": {
            "title": "Meditation, Medicine, and Mind",
            "credits": 1.0,
            "prereqs": [],
            "offered": ["Alternate Years"],
            "gen_ed": ["Humanities"],
            "tags": [],
        },
    },
    "Russian": {
        "RUSS101": {
            "title": "Elementary Russian I",
            "credits": 1.0,
            "prereqs": [],
            "offered": ["Fall"],
            "gen_ed": ["Second Language"],
            "tags": [],
        },
        "RUSS102": {
            "title": "Elementary Russian II",
            "credits": 1.0,
            "prereqs": ["RUSS101"],
            "offered": ["Spring"],
            "gen_ed": ["Second Language"],
            "tags": [],
        },
        "RUSS201": {
            "title": "Intermediate Russian I",
            "credits": 1.0,
            "prereqs": ["RUSS102"],
            "offered": ["Fall"],
            "gen_ed": ["Second Language"],
            "tags": [],
        },
        "RUSS202": {
            "title": "Intermediate Russian II",
            "credits": 1.0,
            "prereqs": ["RUSS201"],
            "offered": ["Spring"],
            "gen_ed": ["Second Language"],
            "tags": [],
        },
    },
    "Sociology": {
        "SOCL 101": {
            "title": "Introduction to Sociology",
            "credits": 1.0,
            "prereqs": [],
            "offered": ["Fall", "Spring"],
            "gen_ed": ["Social Science"],
            "tags": [],
        },
        "SOCL 201L": {
            "title": "Research Methods in the Social Sciences",
            "credits": 1.0,
            "prereqs": ["SOCL 101"],
            "offered": ["Spring"],
            "gen_ed": ["Numerical Reasoning"],
            "tags": [],
        },
        "SOCL 210": {
            "title": "Quantitative Methods for Sociology",
            "credits": 1.0,
            "prereqs": ["SOCL 101", "MATH 107"],
            "offered": ["Fall"],
            "gen_ed": ["Numerical Reasoning"],
            "tags": [],
        },
        "SOCL 214": {
            "title": "Racism (Comparative Study of Race/Ethnicity)",
            "credits": 1.0,
            "prereqs": ["SOCL 101"],
            "offered": ["Alternate Years"],
            "gen_ed": ["Social Science"],
            "tags": [],
        },
        "SOCL 227": {
            "title": "Social Movements",
            "credits": 1.0,
            "prereqs": ["SOCL 101"],
            "offered": ["Alternate Years"],
            "gen_ed": ["Social Science"],
            "tags": [],
        },
        "SOCL 312": {
            "title": "Social Class and Mobility",
            "credits": 1.0,
            "prereqs": ["SOCL 101"],
            "offered": ["Alternate Years"],
            "gen_ed": ["Social Science"],
            "tags": [],
        },
        "SOCL 401": {
            "title": "Senior Seminar in Sociology",
            "credits": 1.0,
            "prereqs": ["Senior Standing"],
            "offered": ["Spring"],
            "gen_ed": ["Writing Emphasis 2"],
            "tags": [],
        },
    },
    "Studio Arts": {
        "ARTS101": {
            "title": "Drawing I",
            "credits": 1.0,
            "prereqs": [],
            "offered": ["Fall", "Spring"],
            "gen_ed": ["Arts"],
            "tags": [],
        },
        "ARTS107": {
            "title": "Painting I",
            "credits": 1.0,
            "prereqs": ["ARTS101"],
            "offered": ["Spring"],
            "gen_ed": ["Arts"],
            "tags": [],
        },
        "ARTS111": {
            "title": "Three-Dimensional Design",
            "credits": 1.0,
            "prereqs": [],
            "offered": ["Fall"],
            "gen_ed": ["Arts"],
            "tags": [],
        },
        "ARTS151": {
            "title": "Photography I",
            "credits": 1.0,
            "prereqs": [],
            "offered": ["Fall", "Spring"],
            "gen_ed": ["Arts"],
            "tags": [],
        },
        "ARTS225": {
            "title": "Digital Art",
            "credits": 1.0,
            "prereqs": [],
            "offered": ["Spring"],
            "gen_ed": ["Arts"],
            "tags": [],
        },
    },
    "Theater & Dance": {
        "THDN101": {
            "title": "Introduction to Theater",
            "credits": 1.0,
            "prereqs": [],
            "offered": ["Fall"],
            "gen_ed": ["Arts"],
            "tags": [],
        },
        "THDN111": {
            "title": "Fundamentals of Acting",
            "credits": 1.0,
            "prereqs": [],
            "offered": ["Fall", "Spring"],
            "gen_ed": ["Arts"],
            "tags": [],
        },
        "THDN123": {
            "title": "Stagecraft",
            "credits": 1.0,
            "prereqs": [],
            "offered": ["Spring"],
            "gen_ed": ["Arts"],
            "tags": [],
        },
        "THDN235": {
            "title": "History of Theater",
            "credits": 1.0,
            "prereqs": [],
            "offered": ["Alternate Years"],
            "gen_ed": ["Humanities"],
            "tags": [],
        },
        "THDN309": {
            "title": "Directing for the Theater",
            "credits": 1.0,
            "prereqs": ["THDN111"],
            "offered": ["Alternate Years"],
            "gen_ed": ["Arts"],
            "tags": [],
        },
    },
    "Women, Gender, and Sexuality": {
        "WMGS101": {
            "title": "Introduction to Women, Gender, and Sexuality",
            "credits": 1.0,
            "prereqs": [],
            "offered": ["Fall", "Spring"],
            "gen_ed": [
                "Social Sciences",
                "Global Engagement",
                "Identity, Power, and Equity",
            ],
            "tags": [],
        },
        "WMGS207": {
            "title": "Gender and Sexuality in a Global World",
            "credits": 1.0,
            "prereqs": [],
            "offered": ["Spring"],
            "gen_ed": ["Social Sciences", "Global Engagement"],
            "tags": [],
        },
        "WMGS301": {
            "title": "Feminist Theories",
            "credits": 1.0,
            "prereqs": ["WMGS101"],
            "offered": ["Fall"],
            "gen_ed": ["Social Sciences", "Writing Emphasis 2"],
            "tags": [],
        },
    },
    "Writing and Rhetoric": {
        "RHET101": {
            "title": "College Writing",
            "credits": 1.0,
            "prereqs": [],
            "offered": ["Fall", "Spring"],
            "gen_ed": ["Writing Emphasis 1"],
            "tags": [],
        },
        "RHET208": {
            "title": "Argument and Exposition",
            "credits": 1.0,
            "prereqs": ["RHET101"],
            "offered": ["Spring"],
            "gen_ed": ["Writing Emphasis 2"],
            "tags": [],
        },
        "RHET225": {
            "title": "Creative Nonfiction",
            "credits": 1.0,
            "prereqs": ["RHET101"],
            "offered": ["Fall"],
            "gen_ed": ["Writing Emphasis 2"],
            "tags": [],
        },
        "RHET302": {
            "title": "Writing Theories and Practice",
            "credits": 1.0,
            "prereqs": ["RHET202"],  # assuming RHET 202 is Writing in the Disciplines
            "offered": ["Alternate Years"],
            "gen_ed": ["Humanities", "Writing Emphasis 2"],
            "tags": [],
        },
    },
}
